require 'sinatra/base'
require 'Sinatra/activerecord'
require_relative 'controllers/app_controller'
require_relative 'controllers/home_controller'
require_relative 'controllers/registrations_controller'
